### PR TITLE
NXP-29435 import small improvements

### PR DESCRIPTION
**Pull request by atchertchian**
Draft PR waiting for #21 to be merged (will have to rebase on master after)

### CODE REVIEW

**Comment by efge** [comment]
Why are thumbnails and picture views listeners a problem? Are there images in the import we don't want to process? Which ones?

**Comment by atchertchian** [comment]
> Why are thumbnails and picture views listeners a problem? Are there images in the import we don't want to process? Which ones?

Thumbnail listeners were originally removed with https://jira.nuxeo.com/browse/NXP-28928.
Basically they're useless costly computations that are not used in the context of this webengine UI, where a lot of documents can be created when snapshoting a distribution: this is a way to optimize this snapshoting.

**Comment by efge** [comment]
> Basically they're useless costly computations that are not used in the context of this webengine UI

Ok I can understand that creating thumbnails for these doc doesn't make sense. But what picture views do we have to process? Or is is just detecting that there is nothing to do which is itself slow?

**Comment by atchertchian** [comment]
> > Basically they're useless costly computations that are not used in the context of this webengine UI
> 
> Ok I can understand that creating thumbnails for these doc doesn't make sense. But what picture views do we have to process? Or is is just detecting that there is nothing to do which is itself slow?

I cannot be 100% sure this is a "real life" issue, because indeed the event listener itself is not supposed to have any effect on explorer document types.
This is still a CI issue in ftests, where reconnected events are piling up for this event (see logs attached to https://jira.nuxeo.com/browse/NXP-29433), sample:

```
2020-08-03T07:58:16,226 WARN  [Nuxeo-Work-default-7:2381990300556297.1652362753] [org.nuxeo.ecm.core.event.impl.ReconnectedEventBundleImpl] Listener 'pictureViewsGenerationListener' cannot refetch missing document: 4b64711a-365b-456a-bdf2-0e2923800dcb (/nuxeo-distributions/my-server-to-delete/Bundles/bg-grp-org-nuxeo-dam/bundle-org-nuxeo-dam/component-org-nuxeo-dam-pageprovider/contrib-org-nuxeo-dam-pageprovider-providers)
2020-08-03T07:58:16,227 WARN  [Nuxeo-Work-default-5:2381990319056330.1140760804] [org.nuxeo.ecm.core.event.impl.ReconnectedEventBundleImpl] Listener 'pictureViewsGenerationListener' cannot refetch missing document: f18d7c5b-c50b-4499-b1a6-4348906d416e (/nuxeo-distributions/my-server-to-delete/Bundles/bg-grp-org-nuxeo-dam/bundle-org-nuxeo-dam/component-org-nuxeo-dam-core-types/contrib-org-nuxeo-dam-core-types-doctype)
2020-08-03T07:58:16,226 WARN  [Nuxeo-Work-default-6:2381990311752993.2038011341] [org.nuxeo.ecm.core.event.impl.ReconnectedEventBundleImpl] Listener 'pictureViewsGenerationListener' cannot refetch missing document: 80723f9c-5221-408d-bd25-01caa0a35737 (/nuxeo-distributions/my-server-to-delete/Bundles/bg-grp-org-nuxeo-dam/bundle-org-nuxeo-dam/component-org-nuxeo-dam-core-types/contrib-org-nuxeo-dam-core-types-schema)
```

I'm trying to reduce unneeded listener processings here, hoping that not having to fetch the document is helping (but looking more closely at the code, i'm now doubting it would have any effect, the doc seems to be fetched again anyway).

Note i reduced the size of the "to be deleted" snapshot being taken in tests to make them more robust (see last commits for https://jira.nuxeo.com/browse/NXP-29433).
If i'm not mistaken, i've also seen these on my local server while importing large distributions.

**Comment by atchertchian** [comment]
Force-pushed to realign on #21

**Review by efge — APPROVED** [review]
Ok it doesn't do any harm but it would be nice to understand what's happening. And maybe add a comment in `fillContextData` explaining why this is done.

**Comment by atchertchian** [comment]
As discussed, the fact that h2 is involved makes it potentially overkill to understand what's happening here.
I will add comments in the code :+1:

**Review by efge — APPROVED** [review]

**Pull request merged**
